# Generated by Django 5.2.11 on 2026-02-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_uuid_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
