# Generated by Django 5.2.11 on 2026-02-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_order_products_orderitem_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
