# Generated by Django 5.2.11 on 2026-02-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
