# Generated by Django 5.2.11 on 2026-03-05 20:28

from django.db import migrations


def add_empty_zone(apps, schema_editor):
    zone = apps.get_model("api", "Zone")
    zone.objects.create(name="Sin asignar")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_zone_remove_product_zone_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.RunPython(add_empty_zone, reverse_code=migrations.RunPython.noop),
    ]
