# Generated by Django 5.2.11 on 2026-03-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_zone_poblation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='zones', to='api.zone'),
        ),
    ]
